### ISSUE TITLE
hra-screen-size-notice-behavior

### ISSUE THREAD

**Issue by axdanbol** [hubmapconsortium/hra-ui#117]
### TODOS
- [ ] Should show when screen width <= 480px
- [ ] On proceed click should show the regular page
- [ ] Saves proceed clicked in local/session storage using state
